[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phantom"
version = "0.1.0"
description = "Pricing Heuristics Against Non-human Transaction Orchestration Mechanisms"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["experiments*", "lib*"]
