ZONE="us-central2-b"
QR_NAME="v4-32-us-spot"
ACCEL_TYPE="v4-32"
RUNTIME_VERSION="v2-alpha-tpuv4"
IS_SPOT="true"
RUN_ID="phantom_v4_spot_1"
HF_REPO="velocitatem/capstone"
TRAIN_CMD="python -m engine.train --sweep-agent --sweep-id lusiana/capstone/oasdorof"