ZONE="europe-west4-a"
QR_NAME="v6e-64-eu-spot"
ACCEL_TYPE="v6e-64"
RUNTIME_VERSION="v2-alpha-tpuv6e"
IS_SPOT="true"
RUN_ID="phantom_v6e_eu_1"
HF_REPO="velocitatem/capstone"
TRAIN_CMD="python -m engine.train --sweep-agent --sweep-id lusiana/capstone/oasdorof"